import type { FoodItem } from "./types"

export const FOOD_ITEMS: FoodItem[] = [
  {
    id: "1",
    name: "Margherita Pizza",
    description: "Fresh tomatoes, mozzarella, and basil",
    price: 14.99,
    image: "/margherita-pizza-basil.png",
    category: "pizza",
    rating: 4.8,
    cookTime: "15-20 min",
    isPopular: true,
  },
  {
    id: "2",
    name: "Classic Beef Burger",
    description: "Juicy beef patty with lettuce, tomato, and cheese",
    price: 12.99,
    image: "/classic-beef-burger.png",
    category: "burgers",
    rating: 4.6,
    cookTime: "10-15 min",
    isPopular: true,
  },
  {
    id: "3",
    name: "Salmon Sushi Roll",
    description: "Fresh salmon with avocado and cucumber",
    price: 16.99,
    image: "/salmon-avocado-sushi.png",
    category: "sushi",
    rating: 4.9,
    cookTime: "5-10 min",
  },
  {
    id: "4",
    name: "Chocolate Cake",
    description: "Rich chocolate cake with cream frosting",
    price: 6.99,
    image: "/chocolate-cake-cream-frosting.png",
    category: "desserts",
    rating: 4.7,
    cookTime: "2-5 min",
  },
  {
    id: "5",
    name: "Fresh Orange Juice",
    description: "Freshly squeezed orange juice",
    price: 4.99,
    image: "/fresh-orange-juice.png",
    category: "drinks",
    rating: 4.5,
    cookTime: "1-2 min",
  },
  {
    id: "6",
    name: "Pepperoni Pizza",
    description: "Classic pepperoni with mozzarella cheese",
    price: 16.99,
    image: "/pepperoni-pizza-with-cheese.png",
    category: "pizza",
    rating: 4.7,
    cookTime: "15-20 min",
    isPopular: true,
  },
]
